### ISSUE TITLE
Tag a release using git commit message does not work

### ISSUE THREAD

**Issue by malibcia** [JoostVoskuil/azure-devops-tagging#4]
I have tried to tag a release using git commit message, but I do not seem to be able to do it.
Could you please advise if this is actually achievable as the description of this task says.

I have tried using $(Build.SourceVersionMessage) but it seems that releases do not have access to this variable.

**Comment by JoostVoskuil** [comment]
Hi @malibcia I am having difficulties understanding what you mean. You can tag git commits, releases and pipelines. What do you want to achieve?

The task can cascade back. So from a Release pipeline, it detects the used build artifacts and by that, what the commit is of the build. It can tag the build commit. However the Release should consume an artifact that is produced by a build.

Can you elaborate what you want to achieve and what your current release/build pipeline is?

**Comment by malibcia** [comment]
Yup, sure.

I need to tag a release. And this tag should be a commit message.
Atm I am doing it like this:
- during the build commit message is build copied over toan external variable in my Library,
- during the release I take the external variable fro Library and update the Tag for a release with it.

So in ADO you have a predefined variable Build.SourceVersionMessage but its scope does not cover deployments. I tought the Tagging would be able to get that, as I understood from the description:
`You can use #currentdate# in the tag or git commit message. This is replace with the current date`
but I guess you also limited this feature and it is not avialable for releases.

Does that make sense?

**Comment by JoostVoskuil** [comment]
You can only use variables that are there to be used by the release. See the 'Initialize job' job for the variables that are there that can be used by default.

The extension works the other way around, you can set a git annotated tag on a commit, not getting a git commit message. I think I've confused you with _'You can use #currentdate# in the tag or git commit message. This is replace with the current date'_ sorry. Will fix that in the docs.

**Comment by JoostVoskuil** [comment]
Closed because of no response
